from typing import List, Dict, Any
from dataclasses import dataclass, field


@dataclass
class AgentPlan:
    """
    Execution plan generated by AgentPlanner.
    """

    steps: List[Dict[str, Any]] = field(
        default_factory=list
    )


class AgentPlanner:


    def __init__(self):

        self.rules = {

            "network": [
                "network",
                "ping",
                "ip",
                "dns",
                "firewall",
                "port"
            ],

            "optimizer": [
                "optimize",
                "performance",
                "improve",
                "speed"
            ],

            "analysis": [
                "analyze",
                "analyse",
                "check",
                "explain"
            ]

        }



    def plan(
        self,
        task
    ) -> AgentPlan:


        text = str(
            task.input
        ).lower()


        steps = []


        selected = "analysis"


        for agent, keywords in self.rules.items():

            matched = False

            for keyword in keywords:

                if keyword in text:
                    selected = agent
                    matched = True
                    break


            if matched:
                break



        steps.append(
            {
                "agent": selected,
                "action": task.action,
                "input": task.input
            }
        )


        return AgentPlan(
            steps=steps
        )
