services:

  ln-neu-core:
    build:
      context: ./backend
    container_name: ln-neu-core
    restart: always

    ports:
      - "8000:3000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://lnneu:lnneu_password@postgres:5432/lnneu



  ln-neu-ai:
    build:
      context: ./ai

    container_name: ln-neu-ai

    restart: always

    ports:
      - "8100:8000"

    depends_on:
      - redis

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      ENVIRONMENT: production
      REDIS_URL: redis://redis:6379
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
      OLLAMA_MODEL: qwen2.5:7b



  ln-neu-ai-worker:
    build:
      context: ./ai

    container_name: ln-neu-ai-worker

    restart: always

    command:
      - python
      - -m
      - task_queue.runner

    depends_on:
      - redis

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      ENVIRONMENT: production
      REDIS_URL: redis://redis:6379
      OLLAMA_URL: http://host.docker.internal:11434/api/generate
      OLLAMA_MODEL: qwen2.5:7b



  redis:
    image: redis:7

    container_name: ln-neu-redis

    restart: always

    ports:
      - "6379:6379"



  postgres:
    image: postgres:16

    container_name: ln-neu-postgres

    restart: always

    environment:
      POSTGRES_USER: lnneu
      POSTGRES_PASSWORD: lnneu_password
      POSTGRES_DB: lnneu

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
